CREATE TABLE POSILJKE(
BROJ_POSILJKE SERIAL PRIMARY KEY,
POSILJALAC VARCHAR(40),
PRIMALAC VARCHAR(40),
STATUS VARCHAR(15));

INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Mila Markovic','Milica Sojevic','poslato');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Snezana Markovic','Dusan Markovic','otpremljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Milica Sojevic','Marija Sojevic','dostavljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Mila Markovic','Dusan Markovic','poslato');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Mila Markovic','Milena Markovic','poslato');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Relja Veinovic','Bojana Sakota','otpremljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Milica Markovic','Mila Markovic','dostavljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Marina Krstic','Luka Tesanovic','dostavljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Mila Markovic','Anja Tomic','otpremljeno');
INSERT INTO POSILJKE (POSILJALAC,PRIMALAC,STATUS) VALUES ('Filip Lutovac','Jovana Nikodijevic','dostavljeno');

SELECT * FROM POSILJKE